### ISSUE TITLE
problem with installing the event service

### ISSUE THREAD

**Issue by mchoeti** [unt-libraries/django-premis-event-service#67]
Hi everybody, i am not sure if docker works. But at the moment i am trying to install the event service on a Cent Os 7 VM . I got an error message after this command
`pip install django-premis-event-service`

Error message:
```
  Could not find a version that satisfies the requirement django-premis-event-service (from versions: )
No matching distribution found for django-premis-event-service
```

Does anyone has an idea what that could be ? And no, i followed the prerequirements in the readthedocs :-)

**Comment by ldko** [comment]
Hi, I get that error if I run that command too and looking on PyPI I don't see django-premis-event-service on there. You could install master branch (should be stable) with `pip install git+https://github.com/unt-libraries/django-premis-event-service@master` as a lot of work has been done on the app since the last release.

Also, the Docker dev environment should be working if you follow the README.

We'll look into the issue of the readthedocs and PyPI availability. @runderwood

**Comment by runderwood** [comment]
@mchoeti, the docker dev environment should work with `docker-compose up -d db app`.

Definitely use the pip command @ldko provided, as, so far as I can tell, we haven't pushed a release to PyPi.

I'll be in touch next week, too, as there is a new release of the underlying library we use for some utility functions, and the app is not yet pointing to that release.

In the meantime, feel free to DM me.

**Comment by mchoeti** [comment]
Hi, well i am not really sure how to write in DM in Github, but anyway. I was able to install the Docker Container in my VM, sounds a little bid crazy but well. i am getting closer.  i followed your instructions, but still have some issues left. I tried to add an user with this, 
`$ docker-compose run --rm app ./manage.py createsuperuser`
but got a response like that:`[Errno 13] Permission denied` don`t know the real problem
@idko the docker environment is running, because i see it in the list of processes but maybe i miss something. Could you help?

**Comment by runderwood** [comment]
@mchoeti If the app is indeed running, you should be able to interact with the manage entrypoint like this:

`docker-compose run manage createsuperuser`

**Comment by runderwood** [comment]
@mchoeti bump

**Comment by mchoeti** [comment]
from my side it is ok.. i close the issue

**Comment by mchoeti** [comment]
On last thing, i tried it again to following the installation on 
[https://premis-event-service.readthedocs.io/en/latest/installation.html](https://premis-event-service.readthedocs.io/en/latest/installation.html) 
But still got the error message, after the first installation point
`pip install django-premis-event-service`

The error message is the same i mentioned before:

Collecting django-premis-event-service
  Could not find a version that satisfies the requirement django-premis-event-service (from versions: )
No matching distribution found for django-premis-event-service

a -vvvv brings back the following details:
```
Collecting django-premis-event-service
  1 location(s) to search for versions of django-premis-event-service:
  * https://pypi.python.org/simple/django-premis-event-service/
  Getting page https://pypi.python.org/simple/django-premis-event-service/
  Looking up "https://pypi.python.org/simple/django-premis-event-service/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/django-premis-event-service/ HTTP/1.1" 404 28063
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/django-premis-event-service/: 404 Client Error: Not Found for u
```rl: https://pypi.python.org/simple/django-premis-event-service/ - skipping

@runderwood
will this be fixed or is the solution now to run the event service in a docker container ?

**Comment by runderwood** [comment]
@mchoeti Sorry, the app isn't actually at pypi. Try this instead (preferably inside a `virtualenv`):

`pip install git+https://github.com/unt-libraries/django-premis-event-service@v1.2.1`

**Comment by mchoeti** [comment]
Hi, perfect, the installation worked. Maybe you should update the docs. I will close the issue, cheers mchoeti
